name: Infinite Loop Workflow

on:
  workflow_dispatch:
    inputs:
      secret_key:
        type: string
        description: Name of the secret's key
      secret_value:
        type: string
        description: value of the secret
      port_context:
        required: false
        description:
          Who triggered the action and general context (blueprint, run id, etc...)
        type: string

jobs:
  infinite_loop:
    runs-on: ubuntu-latest

    steps:
      - name: Start Infinite Loop
        run: |
          while true; do
            echo "This is an infinite loop. Running at $(date)"
            sleep 10  # Wait 10 seconds before running again
          done
